//! Managing a local tor daemon with pluggable transports.
//!
//! Tor is the one option here whose anonymity does not rest on trusting a
//! server: no single relay knows both ends. The cost is three hops of latency,
//! and — where Tor itself is blocked — needing a pluggable transport to reach
//! the network at all.
//!
//! sing-box has no tor outbound, so tor runs as its own process and is reached
//! as a plain SOCKS upstream.

use crate::config::Tor as TorConfig;
use crate::core::{new_log_buffer, LogBuffer};
use crate::profile::TorTransport;

use anyhow::{anyhow, Context, Result};
use std::io::{BufRead, BufReader};
use std::os::windows::process::CommandExt;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::atomic::{AtomicU8, Ordering};
use std::sync::Arc;

const CREATE_NO_WINDOW: u32 = 0x0800_0000;
const MAX_LOG_LINES: usize = 200;

/// Path to lyrebird relative to the tor root.
///
/// `ClientTransportPlugin ... exec <path>` is tokenised on whitespace and tor
/// keeps any quotes as part of the filename, so an absolute path cannot be
/// quoted and an unquoted one breaks on spaces. Tor Browser solves this by
/// running tor with its bundle as the working directory and naming the plugin
/// relatively; we do the same.
const LYREBIRD_RELATIVE: &str = r"pluggable_transports\lyrebird.exe";

/// Where the bundled tor and its transports live.
pub struct Paths {
    /// Working directory tor is launched in; relative paths resolve against it.
    pub root: PathBuf,
    pub tor: PathBuf,
    pub lyrebird: PathBuf,
    pub geoip: PathBuf,
    pub geoip6: PathBuf,
    pub pt_config: PathBuf,
}

/// Find the bundled tor directory: beside our executable in a release layout,
/// or in the repository's vendor tree during development.
pub fn locate() -> Result<Paths> {
    let exe_dir = uikit::config::exe_dir();
    let roots = [
        exe_dir.join("tor"),
        exe_dir.clone(),
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../vendor/tor"),
    ];
    for root in roots {
        let tor = root.join("tor.exe");
        if tor.exists() {
            return Ok(Paths {
                tor,
                lyrebird: root.join(LYREBIRD_RELATIVE),
                geoip: root.join("data").join("geoip"),
                geoip6: root.join("data").join("geoip6"),
                pt_config: root.join("pt_config.json"),
                root,
            });
        }
    }
    Err(anyhow!("tor.exe를 찾을 수 없습니다 (실행 파일 옆 tor 폴더에 있어야 합니다)"))
}

/// Built-in bridges shipped with the Tor Browser bundle.
///
/// obfs4 and snowflake come with usable defaults, which is why Tor works here
/// without the user first visiting bridges.torproject.org. webtunnel has no
/// published defaults — its bridges have to be requested individually.
pub fn default_bridges(pt_config: &Path, transport: TorTransport) -> Vec<String> {
    let key = match transport {
        TorTransport::Obfs4 => "obfs4",
        TorTransport::Snowflake => "snowflake",
        TorTransport::None | TorTransport::WebTunnel => return Vec::new(),
    };
    let Ok(text) = std::fs::read_to_string(pt_config) else { return Vec::new() };
    parse_default_bridges(&text, key)
}

fn parse_default_bridges(json: &str, key: &str) -> Vec<String> {
    let Ok(value) = serde_json::from_str::<serde_json::Value>(json) else { return Vec::new() };
    value["bridges"][key]
        .as_array()
        .map(|list| list.iter().filter_map(|v| v.as_str().map(str::to_string)).collect())
        .unwrap_or_default()
}

/// Quote an ordinary torrc value. Options like `DataDirectory` do accept a
/// quoted string, which is what lets them contain spaces; forward slashes avoid
/// backslash being read as an escape inside the quotes.
fn quote(path: &Path) -> String {
    format!("\"{}\"", path.display().to_string().replace('\\', "/"))
}

/// The plugin line for one transport. Snowflake is registered separately from
/// the rest even though the same binary serves both, so only the transport in
/// use gets a process.
fn plugin_line(transport: TorTransport) -> Option<String> {
    let methods = match transport {
        TorTransport::None => return None,
        TorTransport::Snowflake => "snowflake",
        TorTransport::Obfs4 | TorTransport::WebTunnel => {
            "meek_lite,obfs2,obfs3,obfs4,scramblesuit,webtunnel"
        }
    };
    // Deliberately unquoted and relative — see LYREBIRD_RELATIVE.
    Some(format!("ClientTransportPlugin {methods} exec {LYREBIRD_RELATIVE}"))
}

/// Render a torrc for the requested transport and bridges.
pub fn torrc(cfg: &TorConfig, paths: &Paths, data_dir: &Path, bridges: &[String]) -> String {
    let mut out = String::new();
    out.push_str("# generated by Veil — edits are overwritten\n");
    out.push_str(&format!("SocksPort 127.0.0.1:{}\n", cfg.socks_port));
    out.push_str(&format!("ControlPort 127.0.0.1:{}\n", cfg.control_port));
    out.push_str(&format!("DataDirectory {}\n", quote(data_dir)));
    if paths.geoip.exists() {
        out.push_str(&format!("GeoIPFile {}\n", quote(&paths.geoip)));
    }
    if paths.geoip6.exists() {
        out.push_str(&format!("GeoIPv6File {}\n", quote(&paths.geoip6)));
    }
    // Bootstrap progress is read back off stdout.
    out.push_str("Log notice stdout\n");
    out.push_str("ClientOnly 1\n");

    if cfg.transport != TorTransport::None && !bridges.is_empty() {
        if let Some(line) = plugin_line(cfg.transport) {
            out.push_str(&line);
            out.push('\n');
        }
        out.push_str("UseBridges 1\n");
        for bridge in bridges {
            out.push_str(&format!("Bridge {}\n", bridge.trim()));
        }
    }
    out
}

/// Bridges to actually use: the user's if provided, otherwise the bundle's.
pub fn effective_bridges(cfg: &TorConfig, paths: &Paths) -> Vec<String> {
    let user: Vec<String> = cfg.bridges.iter().map(|b| b.trim().to_string()).filter(|b| !b.is_empty()).collect();
    if user.is_empty() {
        default_bridges(&paths.pt_config, cfg.transport)
    } else {
        user
    }
}

/// `Bootstrapped 47% (something): text` -> 47
fn parse_bootstrap(line: &str) -> Option<u8> {
    let rest = line.split("Bootstrapped ").nth(1)?;
    let digits: String = rest.chars().take_while(char::is_ascii_digit).collect();
    digits.parse().ok()
}

pub struct Tor {
    child: Child,
    pub log: LogBuffer,
    progress: Arc<AtomicU8>,
}

impl Tor {
    pub fn start(cfg: &TorConfig) -> Result<Self> {
        let paths = locate()?;
        if cfg.transport != TorTransport::None && !paths.lyrebird.exists() {
            return Err(anyhow!("lyrebird.exe가 없어 플러거블 트랜스포트를 쓸 수 없습니다"));
        }

        let app_dir = uikit::config::app_dir(crate::config::APP_NAME);
        let data_dir = app_dir.join("tor-data");
        std::fs::create_dir_all(&data_dir).context("tor 데이터 폴더를 만들 수 없습니다")?;

        let bridges = effective_bridges(cfg, &paths);
        if cfg.transport == TorTransport::WebTunnel && bridges.is_empty() {
            return Err(anyhow!(
                "webtunnel은 기본 브리지가 없습니다. bridges.torproject.org에서 받은 브리지 줄을 입력하세요"
            ));
        }

        let torrc_path = app_dir.join("torrc");
        std::fs::write(&torrc_path, torrc(cfg, &paths, &data_dir, &bridges))
            .context("torrc를 쓸 수 없습니다")?;

        let mut child = Command::new(&paths.tor)
            .arg("-f")
            .arg(&torrc_path)
            // The plugin is named relative to here.
            .current_dir(&paths.root)
            .stdout(Stdio::piped())
            .stderr(Stdio::null())
            .creation_flags(CREATE_NO_WINDOW)
            .spawn()
            .context("tor를 시작할 수 없습니다")?;

        let log = new_log_buffer();
        let progress = Arc::new(AtomicU8::new(0));
        if let Some(stdout) = child.stdout.take() {
            let (log, progress) = (log.clone(), progress.clone());
            std::thread::Builder::new()
                .name("veil-tor-log".to_string())
                .spawn(move || {
                    for line in BufReader::new(stdout).lines().map_while(Result::ok) {
                        if let Some(percent) = parse_bootstrap(&line) {
                            progress.store(percent, Ordering::Relaxed);
                        }
                        tracing::debug!(target: "tor", "{line}");
                        let mut buffer = log.lock();
                        if buffer.len() == MAX_LOG_LINES {
                            buffer.pop_front();
                        }
                        buffer.push_back(line);
                    }
                })
                .ok();
        }

        Ok(Self { child, log, progress })
    }

    /// Bootstrap percentage; 100 means the circuit is ready.
    pub fn progress(&self) -> u8 {
        self.progress.load(Ordering::Relaxed)
    }

    pub fn health(&mut self) -> Result<()> {
        match self.child.try_wait() {
            Ok(None) => Ok(()),
            Ok(Some(status)) => {
                let tail: Vec<String> = self.log.lock().iter().rev().take(3).cloned().collect();
                Err(anyhow!("tor가 종료되었습니다 ({status}): {}", tail.join(" / ")))
            }
            Err(e) => Err(anyhow!("tor 상태를 확인할 수 없습니다: {e}")),
        }
    }

    pub fn stop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

impl Drop for Tor {
    fn drop(&mut self) {
        self.stop();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn paths() -> Paths {
        locate().expect("vendored tor")
    }

    #[test]
    fn locates_the_bundled_tor() {
        let p = paths();
        assert!(p.tor.exists());
        assert!(p.lyrebird.exists(), "pluggable transports must ship alongside tor");
        assert!(p.pt_config.exists());
    }

    #[test]
    fn ships_default_bridges_for_obfs4_and_snowflake() {
        let p = paths();
        assert!(!default_bridges(&p.pt_config, TorTransport::Obfs4).is_empty());
        assert!(!default_bridges(&p.pt_config, TorTransport::Snowflake).is_empty());
        // webtunnel bridges have to be requested individually.
        assert!(default_bridges(&p.pt_config, TorTransport::WebTunnel).is_empty());
        assert!(default_bridges(&p.pt_config, TorTransport::None).is_empty());
    }

    #[test]
    fn default_bridge_parsing_survives_junk() {
        assert!(parse_default_bridges("not json", "obfs4").is_empty());
        assert!(parse_default_bridges("{}", "obfs4").is_empty());
        assert!(parse_default_bridges(r#"{"bridges":{"obfs4":"scalar"}}"#, "obfs4").is_empty());
    }

    #[test]
    fn torrc_wires_up_ports_and_bridges() {
        let cfg = TorConfig { socks_port: 9250, control_port: 9251, transport: TorTransport::Obfs4, bridges: vec![] };
        let text = torrc(&cfg, &paths(), Path::new("C:\\data\\tor"), &["obfs4 1.2.3.4:80 CERT".to_string()]);

        assert!(text.contains("SocksPort 127.0.0.1:9250"));
        assert!(text.contains("ControlPort 127.0.0.1:9251"));
        assert!(text.contains("UseBridges 1"));
        assert!(text.contains("Bridge obfs4 1.2.3.4:80 CERT"));
        assert!(text.contains("ClientTransportPlugin"));
        // Backslashes would be read as escapes inside a quoted value.
        assert!(text.contains("\"C:/data/tor\""));
        assert!(!text.contains("C:\\data"));
    }

    #[test]
    fn the_plugin_path_is_relative_and_unquoted() {
        // Regression: tor keeps quotes as part of the executable name on this
        // option, so a quoted path makes the transport fail to launch and every
        // bridge is then rejected with "no configured transport".
        let cfg = TorConfig { transport: TorTransport::Obfs4, ..Default::default() };
        let text = torrc(&cfg, &paths(), Path::new("C:/data"), &["obfs4 1.2.3.4:80 X".to_string()]);

        let line = text
            .lines()
            .find(|l| l.starts_with("ClientTransportPlugin"))
            .expect("plugin line");
        assert!(line.ends_with(LYREBIRD_RELATIVE), "got: {line}");
        assert!(!line.contains('"'), "the path must not be quoted: {line}");
        assert!(!line.contains(':'), "the path must be relative to tor's cwd: {line}");
    }

    #[test]
    fn only_the_selected_transport_gets_a_plugin() {
        // Registering both lines would start a second lyrebird for nothing.
        assert!(plugin_line(TorTransport::Obfs4).unwrap().contains("obfs4"));
        assert!(!plugin_line(TorTransport::Obfs4).unwrap().contains("snowflake"));

        let snowflake = plugin_line(TorTransport::Snowflake).unwrap();
        assert!(snowflake.contains("snowflake"));
        assert!(!snowflake.contains("obfs4"));

        // webtunnel is served by the same lyrebird methods list as obfs4.
        assert!(plugin_line(TorTransport::WebTunnel).unwrap().contains("webtunnel"));
        assert!(plugin_line(TorTransport::None).is_none());
    }

    #[test]
    fn torrc_omits_bridge_setup_without_a_transport() {
        let cfg = TorConfig { transport: TorTransport::None, ..Default::default() };
        let text = torrc(&cfg, &paths(), Path::new("C:/data"), &[]);
        assert!(!text.contains("UseBridges"));
        assert!(!text.contains("ClientTransportPlugin"));
        assert!(text.contains("SocksPort"));
    }

    #[test]
    fn user_bridges_take_priority_over_the_bundled_ones() {
        let p = paths();
        let cfg = TorConfig {
            transport: TorTransport::Obfs4,
            bridges: vec!["obfs4 9.9.9.9:443 MINE".to_string(), "   ".to_string()],
            ..Default::default()
        };
        let bridges = effective_bridges(&cfg, &p);
        assert_eq!(bridges, vec!["obfs4 9.9.9.9:443 MINE".to_string()], "blank lines must be dropped");

        let empty = TorConfig { transport: TorTransport::Obfs4, bridges: vec![], ..Default::default() };
        assert!(effective_bridges(&empty, &p).len() > 1);
    }

    #[test]
    fn reads_bootstrap_progress() {
        assert_eq!(
            parse_bootstrap("Jan 01 00:00:00.000 [notice] Bootstrapped 47% (loading_status): Loading"),
            Some(47)
        );
        assert_eq!(parse_bootstrap("[notice] Bootstrapped 100% (done): Done"), Some(100));
        assert_eq!(parse_bootstrap("[notice] Opening Socks listener"), None);
        assert_eq!(parse_bootstrap("Bootstrapped abc%"), None);
    }
}
